// <auto-generated />
namespace Podelka.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Foreignkey2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Foreignkey2));
        
        string IMigrationMetadata.Id
        {
            get { return "201501122100018_Foreign key2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
