//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Podelka.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountConErrorMessagesVal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountConErrorMessagesVal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Podelka.Resources.AccountConErrorMessagesVal", typeof(AccountConErrorMessagesVal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы обязаны согласиться с правилами, чтобы зарегестрироваться.
        /// </summary>
        public static string AgreeRulesMustBeTrue {
            get {
                return ResourceManager.GetString("AgreeRulesMustBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите {0}.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенные пароли не совпадают.
        /// </summary>
        public static string ConfirmPasswordCompare {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} уже используется.
        /// </summary>
        public static string EmailEqual {
            get {
                return ResourceManager.GetString("EmailEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не должен превышать {1} символов.
        /// </summary>
        public static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ввели недопустимый {0}.
        /// </summary>
        public static string EmailRegular {
            get {
                return ResourceManager.GetString("EmailRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не должно превышать {1} символов.
        /// </summary>
        public static string FirstNameMaxLength {
            get {
                return ResourceManager.GetString("FirstNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не должно быть меньше {1} символов.
        /// </summary>
        public static string FirstNameMinLength {
            get {
                return ResourceManager.GetString("FirstNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} начинается с прописной буквы и может состоять из символов (‘а-я’, пробела и дефиса).
        /// </summary>
        public static string FirstNameRegular {
            get {
                return ResourceManager.GetString("FirstNameRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не должен превышать {1} символов.
        /// </summary>
        public static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не должен быть меньше {1} символов.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} должен содержать хотя бы одну букву и цифру.
        /// </summary>
        public static string PasswordRegular {
            get {
                return ResourceManager.GetString("PasswordRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите адрес по образцу: http://podelka.by.
        /// </summary>
        public static string PersonalWebsiteRegular {
            get {
                return ResourceManager.GetString("PersonalWebsiteRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите номер по подходящему образцу: +375 (**) ***-**-**, +375 (***) **-**-**, +375 (****) *-**-**.
        /// </summary>
        public static string PhoneRegular {
            get {
                return ResourceManager.GetString("PhoneRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите {0}.
        /// </summary>
        public static string RequiredTemplate {
            get {
                return ResourceManager.GetString("RequiredTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не должна превышать {1} символов.
        /// </summary>
        public static string SecondNameMaxLength {
            get {
                return ResourceManager.GetString("SecondNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не должна быть меньше {1} символов.
        /// </summary>
        public static string SecondNameMinLength {
            get {
                return ResourceManager.GetString("SecondNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} начинается с прописной буквы и может состоять из символов (‘а-я’, пробела и дефиса).
        /// </summary>
        public static string SecondNameRegular {
            get {
                return ResourceManager.GetString("SecondNameRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите Фамилию.
        /// </summary>
        public static string SecondNameRequired {
            get {
                return ResourceManager.GetString("SecondNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите адрес по образцу: https://vk.com/podelkaby.
        /// </summary>
        public static string SocialNetworkRegular {
            get {
                return ResourceManager.GetString("SocialNetworkRegular", resourceCulture);
            }
        }
    }
}
